from premier_league_stats import api
from premier_league_stats import data_classes
from premier_league_stats import utils
from premier_league_stats import Fixtures
from premier_league_stats import StatisticsDataManager
from premier_league_stats import main
import premier_league_stats